In [1]:
import cv2
import numpy as np

### 1. Load disparity map, sample image and camera matrix

In [2]:
disparity_map = np.load("../opencv-np-workshop/data/3d/disparity_map.npy")
K = np.load("../opencv-np-workshop/data/camera_params/K.npy")

In [3]:
img1 = cv2.imread("../opencv-np-workshop/data/3d/img1.png")

In [4]:
h, w = disparity_map.shape

In [7]:
focal_length = K[0,0] # Heuristic replacement = 0.8*w (OpenCV documentation) (?)

In [8]:
K

array([[3.57276978e+03, 0.00000000e+00, 2.11492730e+03],
       [0.00000000e+00, 3.58000354e+03, 1.69882805e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [9]:
# Perspective transformation: 
# Matrix to send disparity_map into 3d-space

In [10]:
Q = np.float32([
    [1,0,0,-w/2.],
    [0,-1,0, h/2.],
    [0,0,0,-focal_length],
    [0,0,-1,0]
])

In [11]:
points_3D = cv2.reprojectImageTo3D(disparity_map, Q)

In [13]:
points_3D.shape

(555, 641, 3)

In [15]:
points_3D[0,0] # Representation in 3D space of the pixel at (0,0)

array([ 1.3354167, -1.15625  , 14.88654  ], dtype=float32)

In [17]:
img1.shape

(555, 641, 3)

In [16]:
img1[0,0] # Color of that same point

array([135, 163, 195], dtype=uint8)